name: nrh_ret

model_type: segmented_regression

segmentation_col: general_type

fit_filters:
- unit_price_non_residential > 20
- unit_price_non_residential < 500
- year_built > 1880
- year_built < 2015
- building_sqft > 500
- sale_lease == 'lease'
- general_type == 'Retail'
- zone_id > 0
- node_id > 0
- lease_type == 'NNN'
- building_age < 200

predict_filters:
- county_id==11
- building_type_id==4
- zone_id > 0

min_segment_size: 10

default_config:
    model_expression: np.log1p(unit_price_non_residential) ~ np.log1p(real_far) +
        np.log1p(building_age) + jobs_1_500 + np.log1p(fwy_exit_dist_tdm_output) +
        parcel_volume + jobs_7_500 + train_stn_500 + distmed_4 + distmed_8 + distmed_9
        + distmed_10 +  distmed_12 + distmed_13 + distmed_18 + distmed_19 + distmed_22
        + distmed_23 + distmed_26 + distmed_27 + distmed_28 + distmed_29 + distmed_30
        + distmed_31 + distmed_34 + distmed_35 + distmed_38 + distmed_39 + distmed_40
        + distmed_41 + distmed_42 + distmed_43 + distmed_44 + distmed_45 + distmed_46
        + distmed_51 + distmed_53 + distmed_54 + distmed_55 + distmed_56
    ytransform: np.exp

models:
    Retail:
        fit_parameters:
            Coefficient:
                Intercept: 5.474643290582064
                distmed_13: 0.16319559345793472
                distmed_18: -0.0040439574860654075
                distmed_19: -2.582670292999378e-16
                distmed_22: 0.18759166926220336
                distmed_23: 0.145672752184996
                distmed_26: 2.722152883597649e-16
                distmed_27: -1.592739931816778e-17
                distmed_28: 0.1846907277561792
                distmed_29: 0.007424252559730992
                distmed_30: -0.4272395247771761
                distmed_31: -0.03984882614398821
                distmed_34: 0.17232647386327846
                distmed_35: 0.13077361166089274
                distmed_38: -9.757967552734395e-17
                distmed_39: 1.0219682924849218e-17
                distmed_40: 0.21162526733017445
                distmed_41: -0.0024037956186103854
                distmed_42: -0.05167524757934604
                distmed_43: 0.16816709383035147
                distmed_44: 0.053327274068311316
                distmed_45: 0.1317500426894709
                distmed_46: 0.31978814765966757
                distmed_51: 0.0
                distmed_53: 0.0
                distmed_54: 0.07274610877653742
                distmed_55: 0.2277582524480647
                distmed_56: 0.2277582524480647                
                distmed_4: -1.2549591742457748e-15
                distmed_8: 6.197875417471172e-16
                distmed_9: 4.478985134861432e-16
                distmed_10: 0.05617351418039495
                distmed_12: -0.0941695136815704
                jobs_1_500: 0.0668885170627876
                jobs_7_500: -0.054987389726899205
                np.log1p(building_age): -0.15574051015606308
                np.log1p(fwy_exit_dist_tdm_output): -0.03380166030776365
                np.log1p(real_far): -0.05113185910395861
                parcel_volume: 0.0018845489282930071
                train_stn_500: 0.27596569525975767
            Std. Error:
                Intercept: 0.06212070537553417
                distmed_13: 2.3269915432420096
                distmed_18: -0.056002020557773896
                distmed_19: -2.0669140720660963
                distmed_22: 1.7498806226498338
                distmed_23: 1.8762798881721585
                distmed_26: 3.09259292784368
                distmed_27: -0.32983232657203615
                distmed_28: 1.2409130238318493
                distmed_29: 0.06598308828930521
                distmed_30: -1.602734118296189
                distmed_31: -0.8496698585899697
                distmed_34: 2.408337769755162
                distmed_35: 1.9436003923844372
                distmed_38: -8.675394695694434
                distmed_39: 0.8168268603582156
                distmed_40: 1.7328387267747585
                distmed_41: -0.037569345227910195
                distmed_42: -0.8832678900467448
                distmed_43: 2.3494722287836534
                distmed_44: 1.085804755369088
                distmed_45: 2.8301782544855074
                distmed_46: 1.4657377830206058
                distmed_51: .nan
                distmed_53: .nan
                distmed_54: 0.5908640908676623
                distmed_55: 1.6356523511856729
                distmed_56: 1.6356523511856729                
                distmed_4: -1.1324439531672719
                distmed_8: 1.1541908559191865
                distmed_9: 1.8284686341528908
                distmed_10: 0.5076296869455581
                distmed_12: -1.069015415685936
                jobs_1_500: 0.010177631948155578
                jobs_7_500: 0.01187060425613009
                np.log1p(building_age): 0.012511621025594374
                np.log1p(fwy_exit_dist_tdm_output): 0.040261086961974266
                np.log1p(real_far): 0.01596498089931034
                parcel_volume: 0.0007170464671912373
                train_stn_500: 0.15020314275619848
            T-Score:
                Intercept: 88.12912309167396
                distmed_13: 2.3269915432420096
                distmed_18: -0.056002020557773896
                distmed_19: -2.0669140720660963
                distmed_22: 1.7498806226498338
                distmed_23: 1.8762798881721585
                distmed_26: 3.09259292784368
                distmed_27: -0.32983232657203615
                distmed_28: 1.2409130238318493
                distmed_29: 0.06598308828930521
                distmed_30: -1.602734118296189
                distmed_31: -0.8496698585899697
                distmed_34: 2.408337769755162
                distmed_35: 1.9436003923844372
                distmed_38: -8.675394695694434
                distmed_39: 0.8168268603582156
                distmed_40: 1.7328387267747585
                distmed_41: -0.037569345227910195
                distmed_42: -0.8832678900467448
                distmed_43: 2.3494722287836534
                distmed_44: 1.085804755369088
                distmed_45: 2.8301782544855074
                distmed_46: 1.4657377830206058
                distmed_51: .nan
                distmed_53: .nan
                distmed_54: 0.5908640908676623
                distmed_55: 1.6356523511856729
                distmed_56: 1.6356523511856729                
                distmed_4: -1.1324439531672719
                distmed_8: 1.1541908559191865
                distmed_9: 1.8284686341528908
                distmed_10: 0.5076296869455581
                distmed_12: -1.069015415685936
                jobs_1_500: 6.57211003537118
                jobs_7_500: -4.632231733148985
                np.log1p(building_age): -12.447668438603822
                np.log1p(fwy_exit_dist_tdm_output): -0.8395615433753341
                np.log1p(real_far): -3.2027510353092508
                parcel_volume: 2.6282103246042423
                train_stn_500: 1.8372830967171578
        fit_rsquared: 0.24989068033676676
        fit_rsquared_adj: 0.22657984687331456
        fitted: true
        name: Retail

fitted: true
